name: CI

on:
  push:
    branches: [ 'Feature/e.l.f-brewery-api', 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore "e.l.f. Beauty/e.l.f. Beauty.csproj"

    - name: Build
      run: dotnet build "e.l.f. Beauty/e.l.f. Beauty.sln" --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test "e.l.f. Beauty/e.l.f. Beauty.sln" --no-build --configuration Release --verbosity normal
